name : CI Pipeline - Main
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GIT__BRANCH      : 'main'
  RELEASE_TYPE     : 'major'  
  PACKAGE_NAME     : 'cbr_investment'

jobs:

  increment-tag:
    name: Increment Tag - Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-tests
      - run-qunit-tests

